import{S as f,i as l}from"./assets/vendor-CePATv9e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function g(o){const t=new URLSearchParams({key:"50950053-db3558a1af50bab2399c0c009",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${t}`).then(s=>{if(!s.ok)throw new Error(response.status);return s.json()})}function h(o){let t="";return o.map(s=>{const{webformatURL:a,largeImageURL:e,tags:r,likes:i,views:p,comments:m,downloads:u}=s;t+=`<li class='gallery_item'>
    <a href='${e}' target="_blank">
      <img src='${a}' alt='${r}' class='gallery_img test'/>
      <div class='gallery_info_wrapper'>
        <p class='gallery_info'>Likes <span>${i}</span></p>
        <p class='gallery_info'>Views <span>${p}</span></p>
        <p class='gallery_info'>Comments <span>${m}</span></p>
        <p class='gallery_info'>Downloads <span>${u}</span></p>
      </div>
    </a>
    </li>`}),t}const y=document.querySelector(".form"),d=document.querySelector(".form_input"),n=document.querySelector(".gallery"),c=document.querySelector(".loader");let L=new f(".gallery_item a",{captionsData:"alt",captionDelay:250});y.addEventListener("submit",o=>{o.preventDefault();const t=d.value.trim();if(t===""){l.error({message:"Search value is empty",position:"topRight"});return}n.innerHTML="",n.classList.add("hidden"),c.classList.remove("hidden"),g(t).then(s=>{if(d.value="",s.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c.classList.add("hidden"),n.classList.remove("hidden");return}const a=h(s.hits);n.innerHTML=a,L.refresh()}).catch(s=>{l.error({message:`${s.message||"Something went wrong!"}`,position:"topRight"})}).finally(()=>{c.classList.add("hidden"),n.classList.remove("hidden")})});
//# sourceMappingURL=index.js.map
