import{a as h,S as b,i as d}from"./assets/vendor-BNd6Eq1-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const S="24152486-dede519cf70640e98e72cca28";h.defaults.baseURL="https://pixabay.com/api";async function g(r,t=1,o=15,a="photo",e="horizontal",s=!0){return(await h.get("/",{params:{key:S,q:r,page:t,per_page:o,image_type:a,orientation:e,safesearch:s}})).data}function f(r){let t="";return r.map(o=>{const{webformatURL:a,largeImageURL:e,tags:s,likes:i,views:v,comments:w,downloads:_}=o;t+=`<li class='gallery_item'>
    <a href='${e}' target="_blank">
      <img src='${a}' alt='${s}' class='gallery_img'/>
      <div class='gallery_info_wrapper'>
        <p class='gallery_info'>Likes <span>${i}</span></p>
        <p class='gallery_info'>Views <span>${v}</span></p>
        <p class='gallery_info'>Comments <span>${w}</span></p>
        <p class='gallery_info'>Downloads <span>${_}</span></p>
      </div>
    </a>
    </li>`}),t}const P=document.querySelector(".form"),p=document.querySelector(".form_input"),n=document.querySelector(".gallery"),l=document.querySelector(".loader"),c=document.querySelector("#load_more_btn");let u=1,m="";const y=15;let q=new b(".gallery_item a",{captionsData:"alt",captionDelay:250});P.addEventListener("submit",r=>{if(r.preventDefault(),m=p.value.trim(),m===""){d.error({message:"Search value is empty",position:"topRight"});return}n.innerHTML="",n.classList.add("hidden"),c.classList.add("hidden"),l.classList.remove("hidden"),g(m,u,y).then(t=>{if(p.value="",t.hits.length===0){d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l.classList.add("hidden"),n.classList.remove("hidden");return}const o=f(t.hits);n.innerHTML=o,q.refresh(),c.classList.remove("hidden")}).catch(t=>{d.error({message:`${t.message||"Something went wrong!"}`,position:"topRight"})}).finally(()=>{l.classList.add("hidden"),n.classList.remove("hidden")})});c.addEventListener("click",async()=>{c.classList.add("hidden"),l.classList.remove("hidden"),u+=1;try{const r=await g(m,u);if(r.totalHits===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");const t=f(r.hits);n.innerHTML+=t,l.classList.add("hidden"),L(),R(u,y,r.totalHits),lightbox.refresh()}catch{}});function R(r,t,o){const a=Math.ceil(o/t);if(r>a)return d.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."});L(),c.classList.remove("hidden")}function L(){const r=document.querySelector(".gallery_item")?.getBoundingClientRect().height||0;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
